apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  namespace: so1-clase8
spec:
  selector:
    matchLabels:
      role: deployment1
  replicas: 1
  template:
    metadata:
      labels:
        role: deployment1

    spec:
      containers:
      - name: contenedor1
        image: imagen1
        ports:
        - containerPort: 3300
      - name: contenedor2
        image: imagen2
        ports:
        - containerPort: 50051
  
---
apiVersion: v1
kind: Service
metadata:
  name: service-ejemplo
spec:
  ports:
  - port: 3300
    targetPort: 3300
  selector:
    role: grpc-ruta