apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-clase11
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: d-clase11
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: d-clase11
    spec:
      containers:
      - name: d-clase11
        image: jhonathantocay/clase11
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 2024
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: service-clase11
spec:
  type: LoadBalancer
  ports:
  - port: 2024
    targetPort: 2024
    protocol: TCP
  selector:
    app.kubernetes.io/name: d-clase11