apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: so1-clase8
spec:
  selector:
    matchLabels:
      role: mysql-db
  replicas: 1
  template:
    metadata:
      labels:
        role: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql1234
---
apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  namespace: so1-clase8
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    role: mysql-db