# Define la imagen base de Node.js 18.16.0 en su versión "alpine"
FROM node:18.16.0-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# Copia todo el código fuente de la aplicación al directorio de trabajo del contenedor
COPY . .
EXPOSE 2024

CMD ["node", "index.js"]

# Construye la imagen Docker (asegúrate de ejecutar el comando desde el directorio que contiene el Dockerfile)
# docker build -t clase1_alpine1 .

# Ejecuta un contenedor basado en la imagen que acabas de crear
# docker run -p 2024:2024 clase1_alpine1