version: '3'
services:
  base:
    image: "mysql"
    container_name: 'MYSQL_Base'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql      
    ports:
      - "3306:3306"
  backend:
    image: "jhonathantocay/bclase6"
    container_name: 'Backend'
    environment:
      DB_USER: root
      DB_PASSWORD: so1-mysql123
      DB_HOST: 35.186.188.186
      DB_PORT: 3306
      DB_NAME: clase5
    ports:
      - "2024:2024"
  front:
    image: 'frontend_imagen'
    container_name: 'frontend-React'
    ports:
      - '3000:3000'
volumes:
  base_mysql: 
