FROM node:14-alpine
WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]

#Notas:
#docker build -t front_graphviz .
#docker run -p 3000:3000 front_graphviz