# Define la imagen base de Node.js 18.16.0 en su versión "alpine"
FROM node:18.16.0-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 2024

CMD ["node", "index.js"]

# docker build -t jhonathantocay/bp1 .
# docker push jhonathantocay/bp1
