version: '3'
services:
  base:
    image: "mysql"
    container_name: 'MYSQL_Base'
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
    volumes:
      - base_t:/var/lib/mysql      
    ports:
      - "3306:3306"
  backend:
    build: ./backend 
    image: "imagen_backend"
    container_name: 'Backend_Go'
    ports:
      - "8000:8000"
  frontend:
    image: "imagen_frontend"
    container_name: 'frontend_react'
    ports:
      - "3000:3000"
volumes:
  base_t: 

